### PR TITLE
Use this module inside another module (how?)

### PR DESCRIPTION
**Pull request by cidetraq**
How would that be done? I want to use the functionality of this module without running from the command line, but instead with function calls. I also want to be able to point the file path for the source images to a specified destination, and possibly resize images to fit within the resulting image. Thanks.

### CODE REVIEW

**Comment by hugovk** [comment]
These scripts haven't been written to be used as imported modules, but it shouldn't be too hard to refactor them to be importable.

Please have a look at PR https://github.com/hugovk/pixel-tools/pull/6 for starters.

**Comment by hugovk** [comment]
> I also want to be able to point the file path for the source images to a specified destination, 

You can do that by including the path in the inspec argument:
```python
from image_packer import image_packer


image_packer("/tmp/11*.jpg", "/tmp/out.png", (4048, 4048))
```

---

> ... and possibly resize images to fit within the resulting image. 

Would it suffice to have options to specify what size the input images should be resized to, similar to contact_sheet.py?
```
  -t pixels, --thumbsize pixels
                        Width,height tuple of the photo thumbs (default: None)
  -hs, --half           Shortcut to calculate --thumbsize as half input size
                        (default: False)
  -qs, --quarter        Shortcut to calculate --thumbsize as quarter input
                        size (default: False)
```
https://github.com/hugovk/pixel-tools#contact_sheetpy

**Comment by cidetraq** [comment]
Well, I edited your code to make everything in the if __name__="__main__" statement a function, then calling that function. I edited the default values for arg parser to achieve what I wanted. So it's basically how I want it, even though I don't know how it works with arg parser passing values and all that.

**Comment by hugovk** [comment]
> Well, I edited your code to make everything in the if name="main" statement a function, then calling that function.

Yep, that's the same as I did in the (now-merged) PR #6.

> I edited the default values for arg parser to achieve what I wanted. So it's basically how I want it, even though I don't know how it works with arg parser passing values and all that.

Good to hear you got it working for your needs! I'll close this then, let me know if you've any more questions.

**Pull request closed without merging**
